name: 功能请求
description: "如果想要新功能,请使用这个模板。"
labels: ["功能请求"]
body:
  - type: textarea
    id: description
    attributes: 
      label: 问题描述
      description: 在下方的编辑框描述你想要的功能
      placeholder: |
        请**尽可能简单并全面的**描述。
        勿使用例如“主管！！！主管！！！” “大佬” “搞快点”这类词汇。
        滥用将会导致你被列入黑名单或是被封禁。

        例如：希望添加xxx系统
    validations:
      required: true
  - type: dropdown
    id: type
    attributes: 
      label: 添加类型
      description: |
        选择添加类型
      options: 
        - 娱乐性功能
        - 在现有基础上（例如更新xxx新成就，xxx新层）
        - 新系统（例如宠物系统）
        - 其他
    validations:
      required: true
  - type: textarea
    id: files
    attributes: 
      label: 文件
      description: |
        还可以提供截图和文件（可以直接利用QQ的Ctrl+Alt+A截图后，Ctrl+V粘贴到这个框，或者拖动文件）让我们帮助完善服务器的功能。
      render: text
    validations:
      required: false
  - type: textarea
    id: description
    attributes: 
      label: 其他
      description: 还有什么需要补充的？
      placeholder: |
        请输入
    validations:
      required: true
  - type: checkboxes
    id: agrees
    attributes:
      label: 协议
      description: 功能请求条款
      options:
        - label: 我确认在最新版的阈限天际服务器，并确认功能尚未添加。
          required: true
        - label: 我查阅了所有其他 issues，并已经确认我的请求不是重复的。
          required: true
        - label: 我已知情并同意：需要正确填写 issues 格式，否则此反馈将会被直接锁定。
          required: true
        - label: 我已知情并同意：如果滥用 issues 功能，我会被列入黑名单甚至导致被封禁。
          required: true
        - label: 我确认我没有仔细阅读随便勾选的这些选项。
          required: false
        - label: 我已认真的填写了所有必须的表单选项并正确的描述了它们。
          required: true
